name: Python Check

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install pandas scikit-learn matplotlib seaborn
      - name: Run check
        run: python -c "import pandas; import sklearn; print('All good!')"